# Site settings
title: Data Science Africa, Arusha
email: m.t.smith@sheffield.ac.uk
banner: "Kampala_ug.jpg"
description: > # this means to ignore newlines until "baseurl:"
  The 2016 Data Science Africa summer school held at Makerere University.
baseurl: "/dsa2016" # the subpath of your site, e.g. /blog/
#url: "to do" # the base hostname & protocol for your site
twitter_username: datsciAfrica
logo_url: img/logo.png
#github_username:  SheffieldML
#facebook_page: gaussianprocesssummerschool

# youtube:
  # height: 315
  # width: 560

school:
  name: Data Science in Africa School
  location: Nelson Mandela Institute, Tanzania
  dates:
  - {date: 10, day: Monday, month: July, year: 2017}
  - {date: 11, day: Tuesday, month: July, year: 2017}
  - {date: 12, day: Wednesday, month: July, year: 2017}
  registration:
    deadline:
      date: 6
      month: June
      year: 2017
    open: True
  draft: Y # set to Y if the programme is draft only.

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Mike Smith, url: "http://www.michaeltsmith.org"}
  - {name: Ernest Mwebaze, url: "http://air.ug/~emwebaze"}
  - {name: Mubangizi Martin Gordon, url: "http://air.ug/~mmubangizi"}
  - {name: John Quinn, url: "http://air.ug/~jquinn"}
  - {name: Mike Croucher, url: "http://www.walkingrandomly.com"}
  name: Data Science in Africa Workshop 
  location: Nelson Mandela Institute, Tanzania
  year: 2017
  month: July
  registration
    deadline:
      date: 6
      month: June
      year: 2017
    open: True
  # add other days here for them to appear
  dates:	
  - {date: 13, day: Thursday, month: July, year: 2017}
  - {date: 14, day: Friday, month: July, year: 2017}
  draft: Y # set to Y if the programme is draft only.
  
# Hero
hero:
    # hero_img: hero.jpg
    hero_img: gazzelle.jpg
    hero_img2: 
    hero_title: Data Science
    hero_description: Conference website.

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

sass:
    sass_dir: _scss

# Build settings
markdown: kramdown

