# Site settings
title: Data Science Africa, Arusha
banner: "arusha.jpg"
description: > # this means to ignore newlines until "baseurl:"
  The 2016 Data Science Africa summer school held at Makerere University.
baseurl: "/dsa2017" # the subpath of your site, e.g. /blog/
url: "http://www.datascienceafrica.org" # the base hostname & protocol for your site
twitter_username: datsciAfrica
logo_url: img/logo.png
github_username:  datsciafrica
#facebook_page: gaussianprocesssummerschool

# youtube:
  # height: 315
  # width: 560

previous:
  url: https://sites.google.com/site/dekutdatascienceworkshop2015/
  text: > # From here to school:
>Previous: Data Science Africa 2015 yep!</div>
        <div>June 18<sup>th</sup>  - June 19<sup>th</sup> 2015</div>
        <div>Nyeri, Kenya</div>
school:
  name: Data Science in Africa School
  shortname: DSA2017
  location: "Nelson Mandela Institute, Tanzania"
  googleformid: 5zoTw1jS6w
  dates:		
  - 2017-07-17
  - 2017-07-18
  - 2017-07-19
  registration:
    deadline: 2017-06-26
    open: True
  draft: Y # set to Y if the programme is draft only.
  roles:
  - {name: Mike Smith, url: "http://www.michaeltsmith.org"}
  - {name: Ernest Mwebaze, url: "http://air.ug/~emwebaze"}
  - {name: Mubangizi Martin Gordon, url: "http://air.ug/~mmubangizi"}
  - {name: John Quinn, url: "http://air.ug/~jquinn"}
  - {name: Mike Croucher, url: "http://www.walkingrandomly.com"}

conference:
  shortname: DSA2017
  theme: > # whatever comes from here to hosts:
<p>Using data science to monitor and achieve the global goals in Africa please</p>
<img src="{{site.baseurl}}/img/global_goals.png" style="height:100px">
  hosts:
  roles:
  - {type: General Chair, name: Dina Machuve, url: "http://www.nm-aist.ac.tz"}
  - {type: Program Chair, name: Ciira Maina, url: "https://sites.google.com/site/cwamainadekut/"}
  name: Data Science in Africa Workshop 
  location: Nelson Mandela Institute, Tanzania
  googleformid: Et8ztKOQmo
  year: 2017	
  month: July
  registration:
    deadline: 2017-06-26
    open: True
  # add other days here for them to appear
  dates:	
  - 2017-07-20
  - 2017-07-21
  draft: Y # set to Y if the programme is draft only.
  organizers:
  - {logo: AI.png, name: "AI Research, Makerere University"}
  - {logo: sheffield.png, name: University of Sheffield}
  - {logo: makerere.png, name: Makerere University}
  - {logo: plklogo.png, name: Pulse Lab Kampala}
  - {logo: un_uganda1.png}
  - {logo: dedan_kimathi.jpg, name: Dedan Kimathi University of Technology}
  sponsors:
# Hero
hero:
    # hero_img: hero.jpg
    hero_img: gazzelle.jpg
    hero_img2: 
    hero_title: Data Science
    hero_description: Conference website.

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

sass:
    sass_dir: _scss

# Build settings
markdown: kramdown

