# Site settings
title: Data Science Africa: Kampala
email: m.t.smith@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  The 2016 Data Science Africa summer school held at Makerere University.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "to do" # the base hostname & protocol for your site
twitter_username: datsciAfrica
#github_username:  SheffieldML
#facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Mike Smith, url: "http://www.michaeltsmith.org"}
  # - {name: Alan Saul, url: "http://www.alansaul.com/"}
  #  - {name: Javier Gonzalez, url: "http://javiergonzalezh.github.io/"}
  #  - {name: Zhenwen Dai, url: "http://staffwww.dcs.shef.ac.uk/people/Z.Dai/"}
  #  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Data Science Africa Summer School
  location: Makerere University, Uganda
  year: 2016
  month: June
  # add other days here for them to appear
  dates:	
  - {date: 27, day: Monday, month: June, year: 2016}
  draft: Y # set to Y if the programme is draft only.
# Build settings
markdown: kramdown

