# Site settings
title: Gaussian Process Summer School, Year
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2015 Gaussian Process Summer School held at the University of Sheffield.
baseurl: "/gpschool" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  #  - {name: Javier Gonzalez, url: "http://javiergonzalezh.github.io/"}
  #  - {name: Zhenwen Dai, url: "http://staffwww.dcs.shef.ac.uk/people/Z.Dai/"}
  #  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Gaussian Process Summer School
  location: University of Sheffield, UK
  year: 2015
  month: September
  # add other days here for them to appear
  dates:	
  - {date: 14, day: Monday, month: September, year: 2015}
  
# Build settings
markdown: kramdown

